[package]
description = "Assets Service REST client"
edition     = "2021"                                                       # Allowed values are 2015, 2018, 2021
homepage    = "https://www.arrowair.com/docs/documentation/services/intro"
keywords    = ["vtol", "client", "assets"]                                 # max 5
license     = "BUSL-1.1"
name        = "svc-assets-client-grpc"
repository  = "https://github.com/Arrow-air/svc-assets"
version     = "0.3.0-develop.8"

categories = [
  "aerospace::drones",
  "aerospace::protocols",
] # max 5 -- https://crates.io/category_slugs

[dependencies]
prost       = "0.11"
prost-types = "0.11"
tonic       = "0.8"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
