[package]
description = "Assets Service GRPC client"
keywords    = ["vtol", "client", "assets"] # max 5
name        = "svc-assets-client-grpc"
version     = "0.3.0-develop.11"

authors.workspace      = true
categories.workspace   = true
edition.workspace      = true
homepage.workspace     = true
license-file.workspace = true
repository.workspace   = true

include = ["examples/**", "src/**"]

[dependencies]
prost       = "0.11"
prost-types = "0.11"
tonic       = "0.8"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
