[package]
description = "Arrow assets service REST client"
keywords    = ["vtol", "client", "rest", "assets"] # max 5
name        = "svc-assets-client-rest"
version     = "0.4.1-develop.0"

authors.workspace      = true
categories.workspace   = true
edition.workspace      = true
homepage.workspace     = true
license-file.workspace = true
repository.workspace   = true

[dependencies]
chrono        = { version = "0.4", features = ["serde"] }
ordered-float = { version = "3.4", features = ["serde"] }
serde         = "1.0"
serde_json    = "1.0"

[dependencies.lib-common]
features = ["grpc"]
git      = "https://github.com/Arrow-air/lib-common.git"
tag      = "v0.2.0"

# Get Geo types from storage client
[dependencies.svc-storage-client-grpc]
git = "https://github.com/Arrow-air/svc-storage"
tag = "v0.11.0"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.20", features = ["full"] }

[dependencies.utoipa]
features = ["axum_extras", "chrono"]
version  = "3.3"

[[example]]
name = "rest"
