[package]
description = "Arrow Storage service REST client"
name        = "svc-assets-client-rest"
version     = "0.1.0"

categories.workspace   = true
edition.workspace      = true
homepage.workspace     = true
license-file.workspace = true
repository.workspace   = true

include = ["examples/**", "src/**"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono        = { version = "0.4", features = ["serde"] }
ordered-float = { version = "3.4", features = ["serde"] }
serde         = "1.0"
serde_json    = "1.0"


[[example]]
name = "rest"

[dev-dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.20", features = ["full"] }

[dependencies.utoipa]
features = ["axum_extras", "chrono"]
version  = "2.2"
